// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoexeClient is the client API for Goexe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoexeClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type goexeClient struct {
	cc grpc.ClientConnInterface
}

func NewGoexeClient(cc grpc.ClientConnInterface) GoexeClient {
	return &goexeClient{cc}
}

func (c *goexeClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/proto.Goexe/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoexeServer is the server API for Goexe service.
// All implementations should embed UnimplementedGoexeServer
// for forward compatibility
type GoexeServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

// UnimplementedGoexeServer should be embedded to have forward compatible implementations.
type UnimplementedGoexeServer struct {
}

func (UnimplementedGoexeServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

// UnsafeGoexeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoexeServer will
// result in compilation errors.
type UnsafeGoexeServer interface {
	mustEmbedUnimplementedGoexeServer()
}

func RegisterGoexeServer(s grpc.ServiceRegistrar, srv GoexeServer) {
	s.RegisterService(&Goexe_ServiceDesc, srv)
}

func _Goexe_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoexeServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Goexe/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoexeServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Goexe_ServiceDesc is the grpc.ServiceDesc for Goexe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goexe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Goexe",
	HandlerType: (*GoexeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Goexe_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goexe.proto",
}
